{
 "title": "speedreader",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_runtime_cpu_usage{}" }
   ]
  },
  {
   "title": "cpu seconds total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total{}" }
   ]
  },
  {
   "title": "Time since process start",
   "type": "timeseries",
   "description": "This panel visualizes the maximum duration since the oldest process currently being monitored was started. It calculates the age by subtracting the process start time from the current time, giving insights into the longevity and stability of the longest-running process. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(time() - (process_start_time_seconds))\n"
    }
   ]
  },
  {
   "title": "Total series",
   "type": "timeseries",
   "description": "The total number of active time series in the selected data source. A time series is a unique combination of a metric name and key-value label pairs. For example, “events_total{env=dev}” and “events_total{env=prod}” are two distinct time series, both of which belong to the same parent metric, “events_total.”",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count({__name__=~\".+\"})"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "system_net_http_requests_started{}"
    },
    {
     "expr": "system_net_http_requests_failed{}"
    }
   ]
  },
  {
   "title": "Total Number of Healthy Targets",
   "type": "timeseries",
   "description": "This panel provides a real-time count of all targets that Prometheus is currently able to scrape data from successfully. A target is considered 'up' if the most recent scrape was successful. Tracking the number of 'up' targets allows us to quickly gauge the health and operational status of our systems, ensuring that all necessary components are functioning correctly and are accessible. A significant drop in this number could indicate issues that need immediate attention, such as network failures, system outages, or configuration errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Status of",
   "type": "timeseries",
   "description": "This panel displays the current status of all jobs being scraped by Prometheus. This information is crucial for monitoring the health and performance of the scraping process in real-time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "up{}" }
   ]
  }
 ]
}